### ISSUE TITLE
model duplicate attribute issues

### ISSUE THREAD

**Issue by thirawr** [jsfenfen/990-xml-database#13]
In return.models:
pf_part_vi has two attributes named AppldTESTxAmt that refer to Part VI Line 6c and Part VI Line 11 of the PF respectively.
SkdASpprtdOrgInfrmtn has two attributes named EIN that refer to filer EIN and  Part I Line 12g Column (supported org EIN).
I suspect this is actually an issue with the 990 concordance file / variables sheet as the duplicate issue can be found there as well. I wasn't able to get the default models to migrate to MySQL until I changed `db_name` for one of the two duplicated fields in the variables.csv file that IRSX uses and the corresponding attribute in return.models. The parser runs fine after the fix - I was mostly curious whether you'd encountered this and how you'd addressed it if you had.
(also thanks for this thing it's amazing)

**Comment by jsfenfen** [comment]
Hey @thirawr thanks for noticing this! It's an issue upstream, so I moved it to an issue with the metadata repo [here](https://github.com/jsfenfen/990-xml-metadata/issues/2). Spoiler: I think this is a mysql + case sensitivity thing; needs a fix.

**Comment by thirawr** [comment]
Whoops, shoulda looked there first. Thanks @jsfenfen!
