### ISSUE TITLE
Issue in `variables.csv`

### ISSUE THREAD

**Issue by mjalkio** [jsfenfen/990-xml-database#17]
Hi, I am trying to run the `python manage.py load_metadata` step, and am getting the following error:

```
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/venv/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/venv/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/990-xml-database/irsdb/metadata/management/commands/load_metadata.py", line 95, in handle
    self.reload_variables()
  File "/990-xml-database/irsdb/metadata/management/commands/load_metadata.py", line 26, in reload_variables
    if CANONICAL_VERSION in row['versions']:
KeyError: 'versions'
```

I looked at `vim /venv/lib/python3.6/site-packages/irsx/metadata/variables.csv` and it has these headers `parent_sked,parent_sked_part,in_a_group,db_table,ordering,db_name,xpath,irs_type,db_type,line_number,description,version_start,version_end`. This also seems to be what's present in https://github.com/jsfenfen/990-xml-metadata/blob/master/variables.csv

Am I doing something wrong? Or is this code out of date?

**Comment by jsfenfen** [comment]
Hi @mjalkio thanks for noticing. You're right, the code is outta date. The variables.csv was changed a bit ago and it looks like this change wasn't propagated to this script. I can't remember if this is just an uncommitted change or if there's a fix required, will try to look at soonish.

**Comment by mjalkio** [comment]
Great, thank you!

**Comment by mjalkio** [comment]
Hey @jsfenfen did you have a chance to take a look? We want to leverage this tool but are on a fairly tight timeline. It looks like the metadata update happened back in May and this repo has been updated since then, do you know how that's possible?

**Comment by mjalkio** [comment]
Actually, maybe the issue with `metadata_variable` isn't mine...

```
(venv) root@ip-10-0-6-150:/990-xml-database/irsdb# python manage.py load_metadata
/venv/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Running metadata load on variables.
Deleting variables.
OrderedDict([('parent_sked', 'IRS990'), ('parent_sked_part', 'part_xii'), ('in_a_group', 'False'), ('db_table', 'part_xii'), ('ordering', '622'), ('db_name', 'AccntntCmplOrRvwInd'), ('xpath', '/IRS990/AccountantCompileOrReviewInd'), ('irs_type', 'BooleanType'), ('db_type', 'String(length=5)'), ('line_number', 'Part XII Line 2a'), ('description', 'Accountant provide compilation or review?'), ('version_start', '2013'), ('version_end', '')])
Created 0 rows
Traceback (most recent call last):
  File "/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: relation "metadata_variable" does not exist
```

Do you have any idea where `metadata_variable` is coming from? I printed the row there, seems like the `db_table` should be `part_xii`

**Comment by mjalkio** [comment]
Never mind, user error, I don't think I ran `python manage.py migrate metadata` :)

**Comment by jsfenfen** [comment]
I'd guess 100 GB of uncompressed xml, probably less than 50 GB of db space, not quite sure how that translates to yr setup.
