### ISSUE TITLE
Error when attempting first step of setup.sh

### ISSUE THREAD

**Issue by norbet-sommud** [jsfenfen/990-xml-database#26]
`?: (admin.E403) A 'django.template.backends.django.DjangoTemplates' instance must be configured in TEMPLATES in order to use the admin application.
`

What should I do to resolve this?  IF I need to change my settings again, what does that line mean - sorry for my ignorance.

**Comment by jsfenfen** [comment]
Hi @norbet-sommud I updated [local-settings.py-example](https://github.com/jsfenfen/990-xml-database/blob/master/irsdb/irsdb/local_settings.py-example.py), the template thing it wants is probably there, I forgot to update previously. You'll need to create a copy of that file as local_settings.py and possibly set values that don't make sense. Apologies in advance for the terrible documentation.

**Comment by norbet-sommud** [comment]
@jsfenfen Thank you very much for your updates - I worked w/ a friend to get this working.  I'm able now to at least see 2016 returns and now I'm working through the latter steps of the documentation.  This is a really great product - thank you for making it.
