### ISSUE TITLE
slim down irs generated fields

### ISSUE THREAD

**Issue by jsfenfen** [jsfenfen/990-xml-database#7]
- return_id (varchar (31)): This fields is never NULL, is always 8 characters long and never begins with a zero, so it could be converted to char (8) or even int.
filing_type (varchar (31)): This field is never NULL and is always populated with: "EFILE" Reduce to char (5) or drop the field entirely.
- ein (varchar (31)): This field is never NULL and is always 9 characters. Convert to char (9). Also, the definition lacks the help_text property, which could be set to: "Employer Identification Number"
sub_date (varchar (31)): Sometimes this field includes a time. It would be more useful if it was parsed as datetime; if that's not practical, reduce to varchar (22). It is never NULL.
taxpayer_name (varchar (255)): This field is never NULL and never exceeds 100 characters. Convert to varchar (100).
- return_type (varchar (7)): Never NULL. Reduce to varchar (5).
dln (varchar (31)): Model says this field is "download number," but I think it's actually: "Document Locator Number" and is an amalgamation of seven codes. (Some documentation here: https://www.irs.gov/pub/irs-utl/6209-section4-2012.pdf) This field is never NULL and is always 14 characters long. Change to char (14).
- object_id (varchar (31)): This field is never NULL and is always 18 characters long. It's also always unique and could be used in lieu of adding the id field as a primary key, though populating this table is probably much faster by adding our own key, if this table is indexed.

**Comment by zstumgoren** [comment]
@jsfenfen What's the appropriate strategy for applying field edits/overrides such as this in general? Based on our offline chat, was assuming we'd need to edit or somehow override variables.csv or one of the other [metadata files](https://github.com/jsfenfen/990-xml-reader/tree/master/irs_reader/metadata), but hoping you might clarify. Could be useful to document this kind of thing if it isn't already 😃

**Comment by cschnaars** [comment]
@zstumgoren I think this one model is the exception to that rule.
@jsfenfen Above changes are done. I sent you a pull request.

**Comment by jsfenfen** [comment]
Yeah @zstumgoren, @cschnaars is right, this is the model that holds the *index* information for each filing. For all the fields in return, a change to variables.csv is required.
